### ISSUE TITLE
How to Use in  iPAD

### ISSUE THREAD

**Issue by HarshPandya136** [simformsolutions/SSCustomTabbar#18]
Thanks for this library! Can I use this tabbar in my iPad app?
here I get wave issues in ipad  
I attached ScreenShot. please help As soon as possible

![IMG_2638](https://user-images.githubusercontent.com/54573630/75086545-9ea1a500-555b-11ea-846b-2ef1db1bf188.PNG)

**Comment by vraj-s-shah** [comment]
Yes, you can use in an iPad application. We are aware about the icon issue when app launches and it will be fixed sooner. 

For more information regarding the usage of this library, you can check the Readme [here](https://github.com/SimformSolutionsPvtLtd/SSCustomTabbar#:~:text=4%20years%20ago-,README.md,-SSCustomTabbar).

**Comment by mobile-simformsolutions** [comment]
@HarshPandya136  The icon issue is fixed in the latest release version [2.0.7](https://github.com/SimformSolutionsPvtLtd/SSCustomTabbar/tree/2.0.7).
