### ISSUE TITLE
is it support in lanscape ipad and iphone ?

### ISSUE THREAD

**Issue by rlogical-techsoft** [simformsolutions/SSCustomTabbar#19]

**Comment by khaledbohout2** [comment]
did you find any solution for that?

**Comment by vraj-s-shah** [comment]
Yes, it does support both the portrait and landscape mode, as well as iphone and ipad.

**Comment by mobile-simformsolutions** [comment]
@khaledbohout2 SSCustomTabbar is supported in both the portrait and landscape modes for iPhone and iPad. 


feel free to reopen the issue If you are facing any issues or queries.

Thanks
