### ISSUE TITLE
RTL support ?

### ISSUE THREAD

**Issue by MeryamBenzid** [simformsolutions/SSCustomTabbar#23]
Hello,

I have been trying to fix tab bar to RTL language Can't fix the wave in the right position
I am using Swift

Thank you.

**Comment by basmaamahmoud** [comment]
did you find a solution ?

**Comment by vraj-s-shah** [comment]
@MeryamBenzid It works totally fine when working with RTL languages(tested with several devices) and we are aware about the wave issue and icon not lifted up properly. We had it fixed in the code and will be available in next release itself.

**Comment by mobile-simformsolutions** [comment]
Closing issue due to no new activity. Reopen or create a new issue if face any problems.
