### ISSUE TITLE
Enable subclassing SSCustomTabViewController

### ISSUE THREAD

**Issue by kidvicious** [simformsolutions/SSCustomTabbar#24]
Can you change SSCustomTabViewController and it's methods to open type?

**Comment by vraj-s-shah** [comment]
We cannot make the `SSCustomTabBarViewController` and it's method to open type. If you still wan't to customise the functions, I recommend you to fork the library into your account and customise your library according to your need and use in the application.

**Comment by mobile-simformsolutions** [comment]
@kidvicious can you provide more detail on why you need to make methods open?
is there any special requirement? 

If any improvement or new feature is required, we are happy to add to the library and provide you with more functionality and the feasibility of more customization.

**Comment by kidvicious** [comment]
@mobile-simformsolutions 
hi. i'm afraid this issue was opened a long time ago and can be safely closed.
