### ISSUE TITLE
unable to open file (in target "SSCustomTabbar_Tests" ) 

### ISSUE THREAD

**Issue by KeithGapusan** [simformsolutions/SSCustomTabbar#3]
Hi I'm trying to run the example, but I encounter this error. Do you have any idea to solve this?  thanks
Showing Recent Messages : /Users/SSCustomTabbar-1.2/Example/Pods/Pods/Target Support Files/Pods-SSCustomTabbar_Tests/Pods-SSCustomTabbar_Tests.debug.xcconfig: unable to open file (in target "SSCustomTabbar_Tests" in project "SSCustomTabbar") (in target 'SSCustomTabbar_Tests')

**Comment by simform-solutions** [comment]
@KeithGapusan We are not facing the same issue can you please check again with the latest version of the repository. (https://github.com/simformsolutions/SSCustomTabbar/releases/tag/2.0.2)
