### ISSUE TITLE
push pop bug

### ISSUE THREAD

**Issue by yanmingLiu** [simformsolutions/SSCustomTabbar#4]
<img width="389" alt="WX20190611-161945@2x" src="https://user-images.githubusercontent.com/19849661/59255513-cddde380-8c64-11e9-8728-2c3d46043d71.png">

**Comment by yanmingLiu** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/19849661/61193532-79f46d80-a6ee-11e9-9f74-18ee1d031ec3.png">


![2](https://user-images.githubusercontent.com/19849661/61193486-31d54b00-a6ee-11e9-9378-a783dbb117b0.gif)

<img width="336" alt="image" src="https://user-images.githubusercontent.com/19849661/61193467-1bc78a80-a6ee-11e9-85cc-72ce4e6f84f1.png">

**Comment by KrLikeblue** [comment]
Hey @yanmingLiu : Did you find solution for this ? I had same trouble.

Thanks

**Comment by yanmingLiu** [comment]
> Hey @yanmingLiu : Did you find solution for this ? I had same trouble.
> 
> Thanks

I just think it's good, it's not used in the project.

**Comment by KrLikeblue** [comment]
@simformsolutions Can you please help with me this ?

Thanks

**Comment by simform-solutions** [comment]
@yanmingLiu @KrLikeblue Fixed in release 2.0.2 (https://github.com/simformsolutions/SSCustomTabbar/releases/tag/2.0.2)
