### ISSUE TITLE
Unable to set shadow to Tab bar 

### ISSUE THREAD

**Issue by CearsKhush** [simformsolutions/SSCustomTabbar#5]
Hello, Thank you for this awesome library but I am facing issue while setting shadow to Tab bar I have use following things to set Shadow to Tabbar 

![Screenshot 2019-06-11 at 4 15 01 PM](https://user-images.githubusercontent.com/49678377/59266121-88211b00-8c64-11e9-8817-c38dda1a23ad.png)

Please Help!

**Comment by simform-solutions** [comment]
Hi @CearsKhush ,
Thanks for your response.
For setting shadow to tabBar please try this solution
      `self.layer.shadowOffset = CGSize.zero
        self.layer.shadowRadius = 2
        self.layer.shadowColor = UIColor.black.cgColor
        self.layer.shadowOpacity = 0.3`.
We will update soon.

**Comment by CearsKhush** [comment]
I had already tried this you can see in above screenshot. 
Please check!
