### ISSUE TITLE
wave doesn't move if you change tabs programatically

### ISSUE THREAD

**Issue by georgemckibbin** [simformsolutions/SSCustomTabbar#6]
When I change tabs programmatically with :

`[[[self navigationController] tabBarController] setSelectedIndex:2];`

the wave doesn't move like so

![Simulator Screen Shot - iPhone 6 - 2019-07-24 at 16 41 33](https://user-images.githubusercontent.com/2019928/61771017-08c16280-ae32-11e9-8f43-0a4aeb41fd52.png)

**Comment by CearsKhush** [comment]
Hello @cooliodoc, Did you got any solution?

**Comment by georgemckibbin** [comment]
Hey @CearsKhush unfortunately not. For now I'm just working around it but may have time to look at solving it later.

**Comment by simform-solutions** [comment]
@cooliodoc @CearsKhush fixed in 2.0.2. (https://github.com/simformsolutions/SSCustomTabbar/releases/tag/2.0.2)
