### ISSUE TITLE
How can i stop displaying Tabbar Item?

### ISSUE THREAD

**Issue by CearsKhush** [simformsolutions/SSCustomTabbar#7]
Hello, Thanks for this library! I have some feature like guest login and I want to **Restrict** some tab bar item as If your doesn't logged in then user should not able to open that particular item and instead of this I am going to show some alert for example **Please login first**

Can you please help me with this that how can i Restrict some Tabbar Item?

**Comment by KetanChopda** [comment]
@CearsKhush 

You can use `UITabBarControllerDelegate` for that kind of restriction. 
There is a method `func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool` for that.

You can use same method.
